theme: jekyll-theme-slate
title: Welcome to Marios' page
description: I am Marios and within this page you can find all projects that I've worked on and others that are still merely...notes on a scratchpad! Keep an eye!
